version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/benrowe/http-binary-mapper
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Run unit tests
          command: make test
      - run: make build
      - run: "[[ -x ./bin/proxy ]]"
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
      - persist_to_workspace:
          root: /go/src/github.com/benrowe/http-binary-mapper
          paths:
            - bin
  docker:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo/
      - setup_remote_docker
      - run:
          name: Build the image
          command: |
            docker build
            -t $DOCKER_HUB_USER_ID/http-binary-mapper:$CIRCLE_SHA1
            -t $DOCKER_HUB_USER_ID/http-binary-mapper:latest
            .
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker push $DOCKER_HUB_USER_ID/http-binary-mapper:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/http-binary-mapper:latest

workflows:
  version: 2
  build-docker:
    jobs:
      - build
      - docker:
          filters:
            branches:
              only:
                - master
          requires:
            - build
