version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/benrowe/http-binary-mapper
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Run unit tests
          command: make test
      - run: make
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
